# This file is @generated by tarina.lang CLI tool
# It is not intended for manual editing.

from tarina.lang.model import LangItem, LangModel


class Rater:
    male: LangItem = LangItem("rater", "male")
    female: LangItem = LangItem("rater", "female")
    prompt: LangItem = LangItem("rater", "prompt")
    result: LangItem = LangItem("rater", "result")
    error_timeout: LangItem = LangItem("rater", "error.timeout")
    error_too_large: LangItem = LangItem("rater", "error.too_large")
    error_invalid_input: LangItem = LangItem("rater", "error.invalid_input")
    error_no_face_found: LangItem = LangItem("rater", "error.no_face_found")
    error_no_image_found: LangItem = LangItem("rater", "error.no_image_found")
    error_missing_config: LangItem = LangItem("rater", "error.missing_config")


class Lang(LangModel):
    rater = Rater
